/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package order.services.tool;

import org.junit.Test;
import static org.junit.Assert.*;

public class OrderApplicationTest {
    @Test public void testAppHasAGreeting() {
        OrderApplication classUnderTest = new OrderApplication();
//        assertNotNull("app should have a greeting", classUnderTest.getGreeting());
    }
}
