version: '3'

services:
  docker-mysql:
    image: mysql:latest
    environment:
      MYSQL_DATABASE: orders
      MYSQL_ROOT_PASSWORD: password
      
    ports:
      - "6033:3306"
      
  order-services-app:
    build: ./
    ports:
       - 8080:8080
    depends_on: 
       - docker-mysql
    environment: 
       - SPRING_DATASOURCE_URL=jdbc:mysql://docker-mysql:3306/orders?useUnicode=true&characterEncoding=utf8&useSSL=false